### ISSUE TITLE
Result from async requests

### ISSUE THREAD

**Issue by syed** [swill/csapi#4]
By default the request() method waits for an async request to finish and the returns the result. However the 'jobstatus' in the returned data is still set to `pending` however the polling ensured that the job either failed or succeeded which is not reflected in the return.

**Comment by swill** [comment]
I don't think I understand.  The `jobstatus` is returned by ACS.  It should only be `0` or `1` if I remember correctly.

Can you post some output with an explanation of why you feel it is wrong?

**Comment by swill** [comment]
With the updates you have made, is this issue still an open issue?

**Comment by syed** [comment]
Yeah ... By default the job will be pending when the result of an async request is returned. We poll it so that the job ends but we never update the original response.

**Comment by swill** [comment]
This issue has been resolved with #5 and an offline discussion...
